version: '3.8'

services:
  order-service:
    image: order-service
    build:
      context: ./OrderDemo1  
    ports:
      - "8085:8081"  
    environment:
      - SPRING_CONFIG_LOCATION=/config/application.properties
    depends_on:
      - db_order
    networks:
      - my-network
    volumes:
      - ./OrderDemo1/config/application.properties:/config/application.properties  

  product-service:
    image: product-service
    build:
      context: ./ProductDemo1  
    ports:
      - "8086:8082"  
    environment:
      - SPRING_CONFIG_LOCATION=/config/application.properties
    depends_on:
      - db_product
    networks:
      - my-network
    volumes:
      - ./ProductDemo1/config/application.properties:/config/application.properties

  db_order:
    image: mysql:8
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33061:3306"  
    volumes:
      - db_order_data:/var/lib/mysql  
    networks:
      - my-network

  db_product:
    image: mysql:8
    environment:
      MYSQL_DATABASE: product_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "33062:3306"  
    volumes:
      - db_product_data:/var/lib/mysql  
    networks:
      - my-network

  db_kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://db_kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_order_data:
  db_product_data:


